- name: check pip is installed
  yum: name=python-pip
       state=present

- name: install xs-authserver from pypi
  pip: name=xs-authserver

- name: install gunicorn
  yum: name=python-gunicorn
       state=present

- name: Configure xs-authserver
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner=root
            group=root
            mode={{ item.mode }}
  with_items:
    - src: xs-authserver.env.j2
      dest: /etc/sysconfig/xs-authserver
      mode: 0644
    - src: xs-authserver.service.j2
      dest: /etc/systemd/system/xs-authserver.service
      mode: 0644
      mode: 0644

- name: create database folder
  file: state=directory
        path=/var/lib/xs-authserver/
        owner=root
        group=root
        mode=0644

- name: init database
  command: xs-authserverctl initdb
  ignore_errors: yes
  environment:
    XS_AUTHSERVER_DATABASE: /var/lib/xs-authserver/data.db

- name: Enable xs-authserver service
  service: name=xs-authserver
           enabled=yes
           state=started
