- name: Install python-pip package
  yum: name=python-pip
       state=installed

- name: Install required libraries
  yum: name=${item.pkg}
       state=installed
  with_items:
    - pkg: python-devel
    - pkg: libxslt-devel
    - pkg: pyOpenSSL
    - pkg: python-daemon

- name: install ajenti from Pypi
  pip: name=ajenti version=0.99.34

- name: install python-catcher
  pip: name=python-catcher version=0.1.3

- name: change default port
  lineinfile: dest=/etc/ajenti/config.json
              regexp=' 8000'
              line=' 9990'

- name: exe permission to ajenti
  file: path=/etc/rc.d/init.d/ajenti
        mode=0744

- name: start ajenti service
  service: name=ajenti
           enabled=yes
           state=started
