- name: prepare folder to install wondershaper ajenti plugin
  file: path=/var/lib/ajenti/ajenti-plugin-wondershaper
        state=directory
        group=root
        owner=root

- name: download wondershaper ajenti plugin
  get_url: url=https://github.com/migonzalvar/ajenti-plugin-wondershaper/archive/0.2.tar.gz
           dest=/tmp/ajenti-plugin-wondershaper-0.2.tar.gz

- name: install wondershaper ajenti plugin
  command: tar -xzf /tmp/ajenti-plugin-wondershaper-0.2.tar.gz -C /var/lib/ajenti/ajenti-plugin-wondershaper --strip-components 1 --overwrite --overwrite-dir

- name: link to plugin
  file: state=link
        src=/var/lib/ajenti/ajenti-plugin-wondershaper/wondershaper
        path=/var/lib/ajenti/plugins/wondershaper
        group=root
        owner=root
        mode=0755

- name: restart ajenti service
  service: name=ajenti
           state=restarted
